### ISSUE TITLE
Where is your source code?

### ISSUE THREAD

**Issue by Iamanorange** [falsr/FALSR#2]
Accroding to Lei Jun’s weibo, you have released your source code. So where is your source code?

**Comment by vra** [comment]
@leijun

**Comment by Oktai15** [comment]
Great work, @serser!

It seems that initial code of model didn't appear in this repository. Is it possible to publish it?

**Comment by aikudexiaohai** [comment]
@Iamanorange 雷军只是说模型开源

**Comment by Iamanorange** [comment]
AFAIK "开源" means release source code, not release binary.

**Comment by 871699406** [comment]
Are your code OK？

**Comment by falsr** [comment]
@Oktai15 @Iamanorange  Thanks for the note. In fact, FALSR-A, FALSR-B are sketched out already in the paper, it is possible to build it on your own. Nevertheless, we are going to release that part soon and please stay tuned.

**Comment by Arctanxy** [comment]
重新定义开源

**Comment by zkl99999** [comment]
这也叫开源

**Comment by YuhaoYeSteve** [comment]
Redefine Open Source
